[package]
name = "taskach-backend"
version = "0.1.0"
authors = ["NumbleFingers <numfin>"]
edition = "2018"

[dependencies]
actix-web = "2.0.0"
actix-rt = "1.1.1"
env_logger = "0.7.1"

serde = { version = "1.0.114", features = ["derive"] }
serde_json = "1.0.56"

juniper = "0.14.2"
dotenv = "0.15.0"
uuid = { version = "=0.7.4", features = ["serde", "v4"] }
diesel = { version = "1.4.5", features = ["postgres", "uuidv07", "chrono"] }
chrono = "0.4.13"
