[package]
name = "taskach-backend"
version = "0.1.0"
authors = ["Aleksandr Paramonov <aleksandr.paramonov@vrbank.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
